install.packages("devtools")
library(devtools)
install_github("Alex-Martin1/MandOri")
require(MandOri)
text <- "" #here you should paste your points coordinates as a text input (between always within quotation marks)
result_matrix <- getmatrix(text)
mirror_LM1(result_matrix)
orthoplanes(result_matrix)
mandibular_metrics(result_matrix)
