#' Extract Avizo TCL commands from an orientation result
#'
#' `get_tcl()` retrieves the Avizo TCL command block generated by
#' [orient_mandible()] or [orient_longbone()]. The block can then be pasted into
#' the Avizo/Amira console to orient the relevant Slice and Clipping Plane
#' objects automatically.
#'
#' If `section` is `NULL`, all available TCL blocks are returned as one character
#' string separated by visual dividers. If `section` is specified, only the block
#' for that section is returned.
#'
#' @param res An orientation result returned by [orient_mandible()] or
#'   [orient_longbone()].
#' @param section Optional section name. For mandibular results, expected values
#'   are usually `"CS1"`, `"CS2"`, or `"CS3"`. For long-bone results, expected
#'   values follow the format `"SECTION_35"`, `"SECTION_50"`, and so on.
#'
#' @return A character scalar containing one or more Avizo TCL command blocks.
#'
#' @examples
#' \dontrun{
#' tcl_cs1 <- get_tcl(res, section = "CS1")
#' cat(tcl_cs1)
#' }
#'
#' @export
#'
get_tcl <- function(res, section = NULL) {
  if (is.null(res$avizo_tcl)) {
    stop("The object does not contain `avizo_tcl` blocks.", call. = FALSE)
  }

  if (is.null(section)) {
    return(
      paste(
        unlist(res$avizo_tcl, use.names = FALSE),
        collapse = "\n\n# ------------------------------------------------------------\n\n"
      )
    )
  }

  if (!section %in% names(res$avizo_tcl)) {
    stop(
      sprintf(
        "Section '%s' does not exist. Available sections: %s",
        section, paste(names(res$avizo_tcl), collapse = ", ")
      ),
      call. = FALSE
    )
  }

  res$avizo_tcl[[section]]
}

#' Copy Avizo TCL commands to the system clipboard
#'
#' `copy_tcl()` copies one or more Avizo TCL command blocks from an orientation
#' result to the system clipboard. This is the most direct way to transfer the
#' generated commands from R to the Avizo/Amira console during an interactive
#' image-capture session.
#'
#' @param res An orientation result returned by [orient_mandible()] or
#'   [orient_longbone()].
#' @param section Optional section name. If `NULL`, all available command blocks
#'   are copied.
#'
#' @return Invisibly returns `TRUE` if the copy operation was attempted
#'   successfully. If no supported clipboard mechanism is available, the function
#'   issues a warning and invisibly returns `FALSE`.
#'
#' @examples
#' \dontrun{
#' copy_tcl(res, section = "SECTION_50")
#' }
#'
#' @export
#'
copy_tcl <- function(res, section = NULL) {
  txt <- get_tcl(res, section = section)
  copy_to_clipboard(txt)
}

#' Write Avizo TCL commands to a text file
#'
#' `write_tcl()` writes one or more generated Avizo TCL command blocks to disk.
#' This is useful when command blocks need to be archived with the specimen
#' record, shared with collaborators, or executed later in Avizo/Amira.
#'
#' @param res An orientation result returned by [orient_mandible()] or
#'   [orient_longbone()].
#' @param file Output file path.
#' @param section Optional section name. If `NULL`, all available command blocks
#'   are written.
#'
#' @return Invisibly returns `file`.
#'
#' @examples
#' \dontrun{
#' write_tcl(res, file = "specimen_001_section_50.tcl", section = "SECTION_50")
#' }
#'
#' @export
#'
write_tcl <- function(res, file, section = NULL) {
  txt <- get_tcl(res, section = section)
  writeLines(txt, file)
  invisible(file)
}

# Internal clipboard helper --------------------------------------------------
#
# Use the platform-specific clipboard mechanism available on the user's system.
# Windows uses utils::writeClipboard(); macOS uses pbcopy; Linux attempts xclip
# or xsel. The function is intentionally conservative and returns FALSE rather
# than failing when no clipboard tool is available.
copy_to_clipboard <- function(txt) {
  if (.Platform$OS.type == "windows") {
    utils::writeClipboard(txt)
    return(invisible(TRUE))
  }

  sysname <- Sys.info()[["sysname"]]

  if (identical(sysname, "Darwin")) {
    con <- pipe("pbcopy", "w")
    on.exit(close(con), add = TRUE)
    writeLines(txt, con)
    return(invisible(TRUE))
  }

  if (nzchar(Sys.which("xclip"))) {
    con <- pipe("xclip -selection clipboard", "w")
    on.exit(close(con), add = TRUE)
    writeLines(txt, con)
    return(invisible(TRUE))
  }

  if (nzchar(Sys.which("xsel"))) {
    con <- pipe("xsel --clipboard --input", "w")
    on.exit(close(con), add = TRUE)
    writeLines(txt, con)
    return(invisible(TRUE))
  }

  warning("The block could not be copied to the clipboard automatically.", call. = FALSE)
  invisible(FALSE)
}

#' Print an OrientCSG orientation object
#'
#' The print method provides a compact summary of an orientation result without
#' displaying the full tables or TCL command blocks. It reports the protocol
#' type, the specimen identifier, and the names of the available Avizo TCL
#' blocks.
#'
#' @param x An `orientcsg_orientation` object returned by [orient_mandible()] or
#'   [orient_longbone()].
#' @param ... Additional arguments, currently ignored.
#'
#' @return Invisibly returns `x`.
#'
#' @export
#'
print.orientcsg_orientation <- function(x, ...) {
  cat("OrientCSG orientation result\n")
  cat("Type:", x$type, "\n")
  cat("Individual:", x$individual_id, "\n")

  if (!is.null(x$avizo_tcl)) {
    cat("TCL blocks:", paste(names(x$avizo_tcl), collapse = ", "), "\n")
  }

  invisible(x)
}
