# Internal 3D Slicer Python generator ----------------------------------------
#
# Convert a long-bone orientation result into one Python block per requested
# section. The generated block is intended to be pasted into the 3D Slicer
# Python Interactor with the corresponding mesh model already loaded.
emit_slicer_section_python <- function(res, section = NULL) {
  if (isTRUE(res$USE_ANAT_ORIENT) && !res$type %in% c("TIBIA", "HUMERUS")) {
    stop("3D Slicer output is currently implemented only for `mode = \"TIBIA\"` or `mode = \"HUMERUS\"` when `USE_ANAT_ORIENT = TRUE`.", call. = FALSE)
  }

  if (is.null(section)) {
    section <- names(res$section_points)[1]
  }

  if (!section %in% names(res$section_points)) {
    stop(
      sprintf(
        "Section '%s' does not exist. Available sections: %s",
        section,
        paste(names(res$section_points), collapse = ", ")
      ),
      call. = FALSE
    )
  }

  if (!isTRUE(res$USE_ANAT_ORIENT)) {
    if (is.null(res$vectors$X_screen) || is.null(res$vectors$Y_screen)) {
      stop("Screen-reference vectors are required for section-only Slicer output.", call. = FALSE)
    }
    section_point <- res$section_points[[section]]
    axis_len <- 80
    distal_endpoint <- section_point - 0.5 * axis_len * res$vectors$L
    proximal_endpoint <- section_point + 0.5 * axis_len * res$vectors$L
    anterior_up_sign <- 1
    ml_right_sign <- 1
  } else if (identical(res$type, "TIBIA")) {
    if (is.null(res$projected$Proj_TibioTalar) || is.null(res$projected$Proj_Midpoint)) {
      stop("Projected tibial endpoints are required for Slicer output.", call. = FALSE)
    }
    distal_endpoint <- res$projected$Proj_TibioTalar
    proximal_endpoint <- res$projected$Proj_Midpoint
    # In the current tibial landmark convention, AP points posterior in the
    # generated Slicer view; use -AP as screen-up so anterior appears at the top.
    anterior_up_sign <- -1
    ml_right_sign <- 1
  } else if (identical(res$type, "HUMERUS")) {
    if (is.null(res$projected$Proj_LM3) || is.null(res$projected$Proj_LM4)) {
      stop("Projected humeral endpoints are required for Slicer output.", call. = FALSE)
    }
    distal_endpoint <- res$projected$Proj_LM3
    proximal_endpoint <- res$projected$Proj_LM4
    anterior_up_sign <- 1
    ml_right_sign <- 1
  }

  # OrientCSG stores long-bone geometry internally in the external mesh/LPS-like
  # convention. Slicer Python expects RAS world coordinates, so X and Y are
  # inverted only at this output boundary.
  Psec_ras <- flip_xy(res$section_points[[section]])
  L_ras <- flip_xy(res$vectors$L)
  if (isTRUE(res$USE_ANAT_ORIENT)) {
    ML_ras <- flip_xy(res$vectors$ML)
    AP_ras <- flip_xy(res$vectors$AP)
  } else {
    ML_ras <- flip_xy(res$vectors$X_screen)
    AP_ras <- flip_xy(res$vectors$Y_screen)
  }
  distal_ras <- flip_xy(distal_endpoint)
  proximal_ras <- flip_xy(proximal_endpoint)

  section_percent <- sub("^SECTION_", "", section)

  model_name <- res$model_name
  if (is.null(model_name) || length(model_name) != 1L || is.na(model_name) || !nzchar(model_name)) {
    model_name <- "Segment_1_solid"
  }

  code <- c(
    "import slicer",
    "import vtk",
    "import numpy as np",
    "",
    "# ============================================================",
    "# OrientCSG Slicer section block generated from R",
    "# ============================================================",
    "",
    sprintf("MODEL_NAME = %s", py_quote(model_name)),
    "ALLOW_PARTIAL_MODEL_NAME_MATCH = True",
    "AUTO_SELECT_MODEL_IF_UNAMBIGUOUS = True",
    "",
    sprintf("SECTION_PERCENT = %s", fmt_num_py(as.numeric(section_percent))),
    sprintf("USE_ANATOMICAL_ORIENTATION = %s", if (isTRUE(res$USE_ANAT_ORIENT)) "True" else "False"),
    sprintf("PSEC = %s", fmt_py_vec(Psec_ras)),
    sprintf("L = %s", fmt_py_vec(L_ras)),
    sprintf("ML = %s", fmt_py_vec(ML_ras)),
    sprintf("AP = %s", fmt_py_vec(AP_ras)),
    sprintf("DISTAL_AXIS_POINT = %s", fmt_py_vec(distal_ras)),
    sprintf("PROXIMAL_AXIS_POINT = %s", fmt_py_vec(proximal_ras)),
    "",
    sprintf("CAMERA_DISTANCE_MM = %s", fmt_num_py(res$camera_distance_mm)),
    "VIEW_FROM_PROXIMAL = True",
    "PARALLEL_SCALE_MARGIN = 0.60",
    "CREATE_FILLED_SECTION = True",
    "CREATE_SECTION_OUTLINE_NODE = False",
    sprintf("CREATE_AXIS_LINES = %s", if (isTRUE(res$USE_ANAT_ORIENT)) "True" else "False"),
    "L_AXIS_FULL_LENGTH = True",
    "ML_AP_AXIS_LENGTH_MM = 80.0",
    "CAPTURE_MODE = False",
    "HIDE_ORIGINAL_MODEL_IN_CAPTURE = True",
    sprintf("ANTERIOR_UP_SIGN = %s", fmt_num_py(anterior_up_sign)),
    sprintf("ML_RIGHT_SIGN = %s", fmt_num_py(ml_right_sign)),
    "RULER_COLOR = 0",
    "",
    "def nrm(v):",
    "    v = np.asarray(v, dtype=float)",
    "    s = np.linalg.norm(v)",
    "    if s < 1e-12:",
    "        raise ValueError('Near-zero vector cannot be normalized.')",
    "    return v / s",
    "",
    "def dot3(a, b):",
    "    return float(np.dot(a, b))",
    "",
    "def cross3(a, b):",
    "    return np.cross(a, b)",
    "",
    "def is_output_node(name):",
    "    return name.startswith('SECTION_') or name.startswith('OrientCSG') or name.startswith('Estimated_longitudinal_axis')",
    "",
    "def list_model_nodes():",
    "    print('\\nAvailable vtkMRMLModelNode objects:')",
    "    for i, node in enumerate(slicer.util.getNodesByClass('vtkMRMLModelNode')):",
    "        pd = node.GetPolyData()",
    "        n_points = pd.GetNumberOfPoints() if pd else 0",
    "        n_cells = pd.GetNumberOfCells() if pd else 0",
    "        print(f'  {i+1}. {node.GetName()} | points={n_points} | cells={n_cells}')",
    "",
    "def get_target_model_node():",
    "    plausible = []",
    "    for node in slicer.util.getNodesByClass('vtkMRMLModelNode'):",
    "        name = node.GetName()",
    "        pd = node.GetPolyData()",
    "        if pd is None or pd.GetNumberOfPoints() == 0 or pd.GetNumberOfCells() == 0:",
    "            continue",
    "        if is_output_node(name):",
    "            continue",
    "        plausible.append(node)",
    "    for node in plausible:",
    "        if node.GetName() == MODEL_NAME:",
    "            print(f'Using model node by exact name: \"{node.GetName()}\"')",
    "            return node",
    "    if ALLOW_PARTIAL_MODEL_NAME_MATCH:",
    "        matches = [node for node in plausible if MODEL_NAME.lower() in node.GetName().lower()]",
    "        if len(matches) == 1:",
    "            print(f'Using model node by partial match: \"{matches[0].GetName()}\"')",
    "            return matches[0]",
    "        if len(matches) > 1:",
    "            list_model_nodes()",
    "            raise ValueError('More than one model partially matches MODEL_NAME.')",
    "    if AUTO_SELECT_MODEL_IF_UNAMBIGUOUS and len(plausible) == 1:",
    "        print(f'Auto-selected only plausible model: \"{plausible[0].GetName()}\"')",
    "        return plausible[0]",
    "    list_model_nodes()",
    "    raise ValueError('Could not select target model. Set MODEL_NAME to the exact model name.')",
    "",
    "def clean_previous_outputs():",
    "    prefixes = [",
    "        f'SECTION_{SECTION_PERCENT:g}_outline',",
    "        f'SECTION_{SECTION_PERCENT:g}_filled',",
    "        f'SECTION_{SECTION_PERCENT:g}_L',",
    "        f'SECTION_{SECTION_PERCENT:g}_ML',",
    "        f'SECTION_{SECTION_PERCENT:g}_AP'",
    "    ]",
    "    to_remove = []",
    "    for cls in ['vtkMRMLModelNode', 'vtkMRMLMarkupsLineNode']:",
    "        for node in slicer.util.getNodesByClass(cls):",
    "            name = node.GetName()",
    "            if any(name.startswith(prefix) for prefix in prefixes):",
    "                to_remove.append(node)",
    "    for node in to_remove:",
    "        slicer.mrmlScene.RemoveNode(node)",
    "",
    "def get_model_polydata_world(modelNode):",
    "    polyData = modelNode.GetPolyData()",
    "    transformToWorld = vtk.vtkGeneralTransform()",
    "    slicer.vtkMRMLTransformNode.GetTransformBetweenNodes(modelNode.GetParentTransformNode(), None, transformToWorld)",
    "    tf = vtk.vtkTransformPolyDataFilter()",
    "    tf.SetInputData(polyData)",
    "    tf.SetTransform(transformToWorld)",
    "    tf.Update()",
    "    out = vtk.vtkPolyData()",
    "    out.DeepCopy(tf.GetOutput())",
    "    return out",
    "",
    "def create_section_polydata(polyData, Psec, normal):",
    "    plane = vtk.vtkPlane()",
    "    plane.SetOrigin(float(Psec[0]), float(Psec[1]), float(Psec[2]))",
    "    plane.SetNormal(float(normal[0]), float(normal[1]), float(normal[2]))",
    "    cutter = vtk.vtkCutter()",
    "    cutter.SetCutFunction(plane)",
    "    cutter.SetInputData(polyData)",
    "    cutter.Update()",
    "    clean = vtk.vtkCleanPolyData()",
    "    clean.SetInputData(cutter.GetOutput())",
    "    clean.Update()",
    "    stripper = vtk.vtkStripper()",
    "    stripper.SetInputData(clean.GetOutput())",
    "    stripper.Update()",
    "    out = vtk.vtkPolyData()",
    "    out.DeepCopy(stripper.GetOutput())",
    "    return out",
    "",
    "def triangulate_section(outlinePolyData):",
    "    triangulator = vtk.vtkContourTriangulator()",
    "    triangulator.SetInputData(outlinePolyData)",
    "    triangulator.Update()",
    "    filled = vtk.vtkPolyData()",
    "    filled.DeepCopy(triangulator.GetOutput())",
    "    return filled",
    "",
    "def add_model_node(polyData, name, color=(1.0, 1.0, 1.0), opacity=1.0, line_width=3.0):",
    "    node = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLModelNode', name)",
    "    node.SetAndObservePolyData(polyData)",
    "    node.CreateDefaultDisplayNodes()",
    "    d = node.GetDisplayNode()",
    "    d.SetColor(color)",
    "    d.SetOpacity(opacity)",
    "    d.SetLineWidth(line_width)",
    "    d.SetBackfaceCulling(0)",
    "    d.SetVisibility(True)",
    "    for method_name, value in [('SetLighting', False), ('SetInterpolation', 0), ('SetAmbient', 1.0), ('SetDiffuse', 0.0), ('SetSpecular', 0.0), ('SetPower', 1.0)]:",
    "        try:",
    "            getattr(d, method_name)(value)",
    "        except Exception:",
    "            pass",
    "    return node",
    "",
    "def add_axis_line(name, p1, p2, color=(1.0, 1.0, 1.0)):",
    "    lineNode = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLMarkupsLineNode', name)",
    "    lineNode.CreateDefaultDisplayNodes()",
    "    lineNode.AddControlPointWorld(vtk.vtkVector3d(float(p1[0]), float(p1[1]), float(p1[2])))",
    "    lineNode.AddControlPointWorld(vtk.vtkVector3d(float(p2[0]), float(p2[1]), float(p2[2])))",
    "    d = lineNode.GetDisplayNode()",
    "    d.SetSelectedColor(color)",
    "    d.SetLineThickness(0.35)",
    "    d.SetVisibility(True)",
    "    return lineNode",
    "",
    "def add_centered_axis_line(name, center, direction, length=80.0, color=(1.0, 1.0, 1.0)):",
    "    direction = nrm(direction)",
    "    p1 = center - 0.5 * length * direction",
    "    p2 = center + 0.5 * length * direction",
    "    return add_axis_line(name, p1, p2, color=color)",
    "",
    "def configure_view(threeDView):",
    "    viewNode = threeDView.mrmlViewNode()",
    "    viewNode.SetBackgroundColor(0.0, 0.0, 0.0)",
    "    viewNode.SetBackgroundColor2(0.0, 0.0, 0.0)",
    "    viewNode.SetBoxVisible(False)",
    "    viewNode.SetAxisLabelsVisible(False)",
    "    viewNode.SetOrientationMarkerType(0)",
    "    viewNode.SetRulerType(1)",
    "    try:",
    "        viewNode.SetRulerColor(int(RULER_COLOR))",
    "    except Exception:",
    "        pass",
    "    try:",
    "        viewNode.SetShadowsVisibility(False)",
    "    except Exception:",
    "        pass",
    "    try:",
    "        viewNode.SetRenderMode(viewNode.Orthographic)",
    "    except Exception:",
    "        pass",
    "    viewNode.Modified()",
    "",
    "def widget_size(widget):",
    "    try:",
    "        return int(widget.width), int(widget.height)",
    "    except Exception:",
    "        return int(widget.width()), int(widget.height())",
    "",
    "def compute_camera_basis(L, ML, AP):",
    "    # L is emitted by R as an anatomical distal-to-proximal vector.",
    "    # A proximal view places the camera on the proximal side of the section,",
    "    # instead of choosing the side from any global Slicer axis.",
    "    Zcam = nrm(L)",
    "    if not VIEW_FROM_PROXIMAL:",
    "        Zcam = -Zcam",
    "    desired_up = ANTERIOR_UP_SIGN * AP",
    "    desired_up = desired_up - dot3(desired_up, Zcam) * Zcam",
    "    Ycam = nrm(desired_up)",
    "    desired_right = ML_RIGHT_SIGN * ML",
    "    desired_right = desired_right - dot3(desired_right, Zcam) * Zcam",
    "    desired_right = desired_right - dot3(desired_right, Ycam) * Ycam",
    "    if np.linalg.norm(desired_right) < 1e-12:",
    "        Xcam = nrm(cross3(Ycam, Zcam))",
    "    else:",
    "        Xcam = nrm(desired_right)",
    "    Ycam = nrm(cross3(Zcam, Xcam))",
    "    if dot3(Ycam, desired_up) < 0:",
    "        Xcam = -Xcam",
    "        Ycam = -Ycam",
    "    return Xcam, Ycam, Zcam",
    "",
    "def set_camera(Psec, Xcam, Ycam, Zcam, sectionPolyData):",
    "    threeDView = slicer.app.layoutManager().threeDWidget(0).threeDView()",
    "    cameraNode = threeDView.cameraNode()",
    "    camera = cameraNode.GetCamera()",
    "    configure_view(threeDView)",
    "    C = Psec + CAMERA_DISTANCE_MM * Zcam",
    "    camera.SetPosition(float(C[0]), float(C[1]), float(C[2]))",
    "    camera.SetFocalPoint(float(Psec[0]), float(Psec[1]), float(Psec[2]))",
    "    camera.SetViewUp(float(Ycam[0]), float(Ycam[1]), float(Ycam[2]))",
    "    camera.ParallelProjectionOn()",
    "    camera.OrthogonalizeViewUp()",
    "    if sectionPolyData is not None and sectionPolyData.GetNumberOfPoints() > 0:",
    "        pts = sectionPolyData.GetPoints()",
    "        coords = np.array([pts.GetPoint(i) for i in range(pts.GetNumberOfPoints())], dtype=float)",
    "        rel = coords - Psec",
    "        x = rel @ Xcam",
    "        y = rel @ Ycam",
    "        span_x = max(1.0, float(np.max(x) - np.min(x)))",
    "        span_y = max(1.0, float(np.max(y) - np.min(y)))",
    "        width, height = widget_size(threeDView)",
    "        aspect = max(1.0, width / max(1, height))",
    "        camera.SetParallelScale(PARALLEL_SCALE_MARGIN * max(span_y, span_x / aspect))",
    "    else:",
    "        camera.SetParallelScale(40.0)",
    "    camera.SetClippingRange(1.0, 5000.0)",
    "    cameraNode.Modified()",
    "    threeDView.forceRender()",
    "    return camera",
    "",
    "def save_camera_state(modelNode, camera):",
    "    modelNode.SetAttribute('OrientCSG.CameraPosition', ','.join([f'{v:.12g}' for v in camera.GetPosition()]))",
    "    modelNode.SetAttribute('OrientCSG.CameraFocalPoint', ','.join([f'{v:.12g}' for v in camera.GetFocalPoint()]))",
    "    modelNode.SetAttribute('OrientCSG.CameraViewUp', ','.join([f'{v:.12g}' for v in camera.GetViewUp()]))",
    "    modelNode.SetAttribute('OrientCSG.CameraParallelScale', f'{camera.GetParallelScale():.12g}')",
    "",
    "def restore_orientcsg_camera_state(modelNode=None):",
    "    if modelNode is None:",
    "        modelNode = get_target_model_node()",
    "    threeDView = slicer.app.layoutManager().threeDWidget(0).threeDView()",
    "    cameraNode = threeDView.cameraNode()",
    "    camera = cameraNode.GetCamera()",
    "    pos_txt = modelNode.GetAttribute('OrientCSG.CameraPosition')",
    "    foc_txt = modelNode.GetAttribute('OrientCSG.CameraFocalPoint')",
    "    up_txt = modelNode.GetAttribute('OrientCSG.CameraViewUp')",
    "    scale_txt = modelNode.GetAttribute('OrientCSG.CameraParallelScale')",
    "    if None in [pos_txt, foc_txt, up_txt, scale_txt]:",
    "        raise ValueError('No saved OrientCSG camera state found.')",
    "    pos = [float(x) for x in pos_txt.split(',')]",
    "    foc = [float(x) for x in foc_txt.split(',')]",
    "    up = [float(x) for x in up_txt.split(',')]",
    "    scale = float(scale_txt)",
    "    configure_view(threeDView)",
    "    camera.SetPosition(*pos)",
    "    camera.SetFocalPoint(*foc)",
    "    camera.SetViewUp(*up)",
    "    camera.SetParallelScale(scale)",
    "    camera.ParallelProjectionOn()",
    "    camera.OrthogonalizeViewUp()",
    "    cameraNode.Modified()",
    "    threeDView.forceRender()",
    "",
    "clean_previous_outputs()",
    "modelNode = get_target_model_node()",
    "modelNode.CreateDefaultDisplayNodes()",
    "polyDataWorld = get_model_polydata_world(modelNode)",
    "sectionOutline = create_section_polydata(polyDataWorld, PSEC, L)",
    "if sectionOutline.GetNumberOfPoints() == 0:",
    "    raise ValueError('The section plane did not intersect the model.')",
    "sectionFilledNode = None",
    "if CREATE_FILLED_SECTION:",
    "    sectionFilled = triangulate_section(sectionOutline)",
    "    if sectionFilled.GetNumberOfCells() > 0:",
    "        sectionFilledNode = add_model_node(sectionFilled, name=f'SECTION_{SECTION_PERCENT:g}_filled', color=(1.0, 1.0, 1.0), opacity=1.0, line_width=1.0)",
    "    else:",
    "        print('WARNING: Could not triangulate filled section.')",
    "sectionOutlineNode = None",
    "if CREATE_SECTION_OUTLINE_NODE:",
    "    sectionOutlineNode = add_model_node(sectionOutline, name=f'SECTION_{SECTION_PERCENT:g}_outline', color=(1.0, 1.0, 1.0), opacity=1.0, line_width=4.0)",
    "if CREATE_AXIS_LINES:",
    "    if L_AXIS_FULL_LENGTH:",
    "        add_axis_line(f'SECTION_{SECTION_PERCENT:g}_L', DISTAL_AXIS_POINT, PROXIMAL_AXIS_POINT, color=(0.0, 1.0, 0.0))",
    "    else:",
    "        add_centered_axis_line(f'SECTION_{SECTION_PERCENT:g}_L', PSEC, L, length=np.linalg.norm(PROXIMAL_AXIS_POINT - DISTAL_AXIS_POINT), color=(0.0, 1.0, 0.0))",
    "    add_centered_axis_line(f'SECTION_{SECTION_PERCENT:g}_ML', PSEC, ML, length=ML_AP_AXIS_LENGTH_MM, color=(0.0, 0.4, 1.0))",
    "    add_centered_axis_line(f'SECTION_{SECTION_PERCENT:g}_AP', PSEC, AP, length=ML_AP_AXIS_LENGTH_MM, color=(1.0, 0.0, 0.0))",
    "d = modelNode.GetDisplayNode()",
    "if CAPTURE_MODE and HIDE_ORIGINAL_MODEL_IN_CAPTURE:",
    "    d.SetVisibility(False)",
    "else:",
    "    d.SetVisibility(True)",
    "    d.SetOpacity(0.22)",
    "Xcam, Ycam, Zcam = compute_camera_basis(L, ML, AP)",
    "camera = set_camera(PSEC, Xcam, Ycam, Zcam, sectionOutline)",
    "save_camera_state(modelNode, camera)",
    "",
    "print('\\n================ ORIENTCSG / SLICER SECTION ================\\n')",
    "print('Model:', modelNode.GetName())",
    "print('Section percent:', SECTION_PERCENT)",
    "print('\\nPSEC, Slicer RAS:')",
    "print(PSEC)",
    "print('\\nL, ML, AP, Slicer RAS:')",
    "print(L)",
    "print(ML)",
    "print(AP)",
    "print('\\nCreated model nodes:')",
    "if sectionFilledNode is not None:",
    "    print(sectionFilledNode.GetName())",
    "if sectionOutlineNode is not None:",
    "    print(sectionOutlineNode.GetName())",
    "else:",
    "    print('No outline model node was created.')",
    "if CREATE_AXIS_LINES:",
    "    print('\\nAxis lines: L green, ML blue, AP red')",
    "else:",
    "    print('\\nSection-only mode: anatomical axis lines were not created.')",
    "print('Ruler visible, requested color enum:', RULER_COLOR)",
    "print('To restore this view later, run: restore_orientcsg_camera_state()')"
  )

  paste(code, collapse = "\n")
}

# Internal 3D Slicer Python generator for mandibles --------------------------
#
# Convert a mandibular orientation result into one Python block per planned
# section. The generated code orients a Slicer slice view to the same section
# plane used by the Avizo/Amira backend. Internally OrientCSG stores all points
# and vectors in LPS/external coordinates; the Python block receives RAS values.
emit_slicer_mandible_python <- function(res, section = NULL) {
  available_sections <- c("CS1", "CS2", "CS3")

  if (is.null(section)) {
    section <- available_sections[1]
  }

  section <- toupper(trimws(section))
  if (!section %in% available_sections) {
    stop(
      sprintf(
        "Section '%s' does not exist. Available sections: %s",
        section,
        paste(available_sections, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  LM <- res$landmarks
  LM2 <- LM["LM2", ]
  Vec_LandmarkedSide <- res$vectors$Vec_LandmarkedSide

  if (section == "CS1") {
    Psec <- res$points$CS1B
    normal <- res$vectors$Vec_CS1_Normal
    x_ref <- project_vector_to_plane(res$vectors$Vec_CS1, normal)

    if (dot3(normal, Vec_LandmarkedSide) < 0) {
      normal <- -normal
    }
    three_d_side <- "PLUS"
  } else if (section == "CS2") {
    Psec <- res$points$CS2B
    normal <- res$vectors$Vec_CS2_Normal
    x_ref <- project_vector_to_plane(res$vectors$Vec_CS2, normal)

    if (dot3(normal, Vec_LandmarkedSide) < 0) {
      normal <- -normal
    }
    three_d_side <- "PLUS"
  } else {
    Psec <- LM2
    normal <- res$vectors$Vec_RightToLeft
    x_ref <- res$vectors$Vec_0_2

    if (dot3(normal, Vec_LandmarkedSide) < 0) {
      normal <- -normal
    }
    three_d_side <- "PLUS"
  }

  if (sqrt(sum(x_ref^2)) < 1e-12) {
    stop(sprintf("%s: screen-horizontal reference vector cannot be defined.", section), call. = FALSE)
  }

  # OrientCSG stores mandibular coordinates internally in LPS. 3D Slicer Python
  # expects RAS world coordinates, so X and Y are inverted only at this output
  # boundary.
  Psec_ras <- flip_xy(Psec)
  normal_ras <- flip_xy(normal)
  x_ref_ras <- flip_xy(x_ref)
  y_pref_ras <- flip_xy(res$vectors$Vec_Penp)
  arp_origin_ras <- flip_xy(res$points$ARP_Origin)
  arp_normal_ras <- flip_xy(res$vectors$Vec_Penp)
  lm1_line_ras <- flip_xy(res$points$LM1_Line)

  volume_name <- res$volume_name
  if (is.null(volume_name) || length(volume_name) != 1L || is.na(volume_name) || !nzchar(volume_name)) {
    volume_name <- ""
  }

  code <- c(
    "import slicer",
    "import vtk",
    "import numpy as np",
    "",
    "# ============================================================",
    "# OrientCSG / Mandible / Slicer Python block generated from R",
    "# Coordinates emitted in Slicer RAS world space",
    "# ============================================================",
    "",
    sprintf("VOLUME_NAME = %s", py_quote(volume_name)),
    sprintf("SECTION_LABEL = %s   # \"CS1\", \"CS2\", or \"CS3\"", py_quote(section)),
    "SLICE_VIEW_NAME = \"Red\"",
    "",
    "# Display controls",
    "FIELD_OF_VIEW_MM = 85.0",
    sprintf("CAMERA_DISTANCE_MM = %s", fmt_num_py(res$camera_distance_mm)),
    "VOLUME_RENDERING_PRESET = \"CT-AAA2\"",
    "",
    "CREATE_SCALE_BAR = True",
    "SCALE_BAR_LENGTH_MM = 10.0",
    "SCALE_BAR_MARGIN_MM = 3.0",
    "",
    "CREATE_ARP_PLANE = True",
    "CREATE_LM1_LINE_POINT = True",
    "",
    "LOCK_RED_SLICE_BROWSING = True",
    "",
    "# 3D verification view:",
    "# The 3D camera is oriented so that:",
    "# - the ARP appears edge-on as a horizontal line",
    "# - the current section plane appears edge-on as a vertical line",
    "# - both planes are perpendicular to the screen",
    sprintf("THREED_VERIFICATION_VIEW_SIDE = %s  # \"PLUS\" or \"MINUS\"", py_quote(three_d_side)),
    "",
    sprintf("PSEC = %s", fmt_py_vec(Psec_ras)),
    sprintf("NORMAL = %s", fmt_py_vec(normal_ras)),
    sprintf("X_SCREEN_REFERENCE = %s", fmt_py_vec(x_ref_ras)),
    sprintf("Y_PREFERRED = %s", fmt_py_vec(y_pref_ras)),
    sprintf("ARP_ORIGIN = %s", fmt_py_vec(arp_origin_ras)),
    sprintf("ARP_NORMAL = %s", fmt_py_vec(arp_normal_ras)),
    sprintf("LM1_LINE = %s", fmt_py_vec(lm1_line_ras)),
    "",
    "def nrm(v):",
    "    v = np.asarray(v, dtype=float)",
    "    s = np.linalg.norm(v)",
    "    if s < 1e-12:",
    "        raise ValueError(\"Near-zero vector cannot be normalized.\")",
    "    return v / s",
    "",
    "def dot3(a, b):",
    "    return float(np.dot(a, b))",
    "",
    "def cross3(a, b):",
    "    return np.cross(a, b)",
    "",
    "def project_vector_to_plane(v, normal):",
    "    normal = nrm(normal)",
    "    return np.asarray(v, dtype=float) - dot3(v, normal) * normal",
    "",
    "def find_volume_node(name):",
    "    candidates = slicer.util.getNodesByClass(\"vtkMRMLScalarVolumeNode\")",
    "",
    "    if name:",
    "        exact = [node for node in candidates if node.GetName() == name]",
    "        if len(exact) == 1:",
    "            return exact[0]",
    "",
    "        partial = [node for node in candidates if name.lower() in node.GetName().lower()]",
    "        if len(partial) == 1:",
    "            print(f'Using partial volume-name match: \"{partial[0].GetName()}\"')",
    "            return partial[0]",
    "",
    "        print(\"Available scalar volumes:\")",
    "        for node in candidates:",
    "            print(\"  \", node.GetName())",
    "",
    "        if len(exact) > 1 or len(partial) > 1:",
    "            raise ValueError(f'More than one volume matches \"{name}\". Use the exact Slicer node name.')",
    "        raise ValueError(f'Could not find a scalar volume named \"{name}\".')",
    "",
    "    lm = slicer.app.layoutManager()",
    "    sliceWidget = lm.sliceWidget(SLICE_VIEW_NAME)",
    "    if sliceWidget is not None:",
    "        comp = sliceWidget.sliceLogic().GetSliceCompositeNode()",
    "        if comp is not None and comp.GetBackgroundVolumeID():",
    "            node = slicer.mrmlScene.GetNodeByID(comp.GetBackgroundVolumeID())",
    "            if node is not None:",
    "                return node",
    "",
    "    if len(candidates) == 1:",
    "        return candidates[0]",
    "",
    "    print(\"Available scalar volumes:\")",
    "    for node in candidates:",
    "        print(\"  \", node.GetName())",
    "    raise ValueError(\"Set VOLUME_NAME explicitly when zero or multiple scalar volumes are loaded.\")",
    "",
    "def remove_old_orientcsg_nodes():",
    "    prefixes = [",
    "        \"OrientCSG_mandible_\",",
    "        \"OrientCSG_ARP\",",
    "        \"OrientCSG_scale\",",
    "        \"OrientCSG_LM1_Line\"",
    "    ]",
    "    to_remove = []",
    "    for cls in [",
    "        \"vtkMRMLMarkupsFiducialNode\",",
    "        \"vtkMRMLMarkupsLineNode\",",
    "        \"vtkMRMLMarkupsPlaneNode\"",
    "    ]:",
    "        for node in slicer.util.getNodesByClass(cls):",
    "            if any(node.GetName().startswith(prefix) for prefix in prefixes):",
    "                to_remove.append(node)",
    "    for node in to_remove:",
    "        slicer.mrmlScene.RemoveNode(node)",
    "",
    "def remove_old_scale_nodes():",
    "    prefixes = [\"OrientCSG_scale\"]",
    "    to_remove = []",
    "    for cls in [",
    "        \"vtkMRMLMarkupsFiducialNode\",",
    "        \"vtkMRMLMarkupsLineNode\"",
    "    ]:",
    "        for node in slicer.util.getNodesByClass(cls):",
    "            if any(node.GetName().startswith(prefix) for prefix in prefixes):",
    "                to_remove.append(node)",
    "    for node in to_remove:",
    "        slicer.mrmlScene.RemoveNode(node)",
    "",
    "def make_slice_to_ras(point, z_axis, x_reference, y_preferred):",
    "    point = np.asarray(point, dtype=float)",
    "",
    "    # Z screen axis: normal vector of the cross-sectional plane.",
    "    z_axis = nrm(z_axis)",
    "",
    "    # Y screen axis: anatomical vertical in the section view.",
    "    # It is defined as the ARP normal projected into the current section plane.",
    "    # This forces the ARP to appear horizontal in the captured slice.",
    "    y_axis = np.asarray(y_preferred, dtype=float)",
    "    y_axis = y_axis - dot3(y_axis, z_axis) * z_axis",
    "",
    "    if np.linalg.norm(y_axis) < 1e-12:",
    "        raise ValueError(",
    "            \"Cannot construct anatomical slice axes: y_preferred is collinear with the section normal.\"",
    "        )",
    "",
    "    y_axis = nrm(y_axis)",
    "",
    "    # X screen axis: horizontal axis of the image.",
    "    # This corresponds to the line of intersection between the ARP and the section plane.",
    "    x_axis = nrm(cross3(y_axis, z_axis))",
    "",
    "    # Use the emitted X_SCREEN_REFERENCE only to choose the left-right sign.",
    "    # This does not change the fact that Y screen is controlled by the ARP normal.",
    "    x_ref = np.asarray(x_reference, dtype=float)",
    "    x_ref = x_ref - dot3(x_ref, z_axis) * z_axis",
    "",
    "    if np.linalg.norm(x_ref) > 1e-12:",
    "        if dot3(x_axis, nrm(x_ref)) < 0:",
    "            # Preserve anatomical Y-up. Flip the slice normal instead of",
    "            # flipping Y; this keeps superior at the top while changing the",
    "            # side from which the section is viewed.",
    "            z_axis = -z_axis",
    "            x_axis = nrm(cross3(y_axis, z_axis))",
    "",
    "    # Defensive re-orthogonalization that preserves Y as anatomical up.",
    "    x_axis = nrm(cross3(y_axis, z_axis))",
    "    z_axis = nrm(cross3(x_axis, y_axis))",
    "",
    "    m = vtk.vtkMatrix4x4()",
    "    m.Identity()",
    "",
    "    for i in range(3):",
    "        m.SetElement(i, 0, float(x_axis[i]))",
    "        m.SetElement(i, 1, float(y_axis[i]))",
    "        m.SetElement(i, 2, float(z_axis[i]))",
    "        m.SetElement(i, 3, float(point[i]))",
    "",
    "    return m, x_axis, y_axis, z_axis",
    "",
    "def get_slice_node_and_widget():",
    "    lm = slicer.app.layoutManager()",
    "    sliceWidget = lm.sliceWidget(SLICE_VIEW_NAME)",
    "    if sliceWidget is None:",
    "        raise ValueError(f'Could not find slice view \"{SLICE_VIEW_NAME}\".')",
    "    sliceLogic = sliceWidget.sliceLogic()",
    "    sliceNode = sliceLogic.GetSliceNode()",
    "    return sliceWidget, sliceLogic, sliceNode",
    "",
    "def get_current_slice_axes():",
    "    sliceWidget, sliceLogic, sliceNode = get_slice_node_and_widget()",
    "    m = sliceNode.GetSliceToRAS()",
    "",
    "    x_axis = np.array([m.GetElement(0, 0), m.GetElement(1, 0), m.GetElement(2, 0)], dtype=float)",
    "    y_axis = np.array([m.GetElement(0, 1), m.GetElement(1, 1), m.GetElement(2, 1)], dtype=float)",
    "    z_axis = np.array([m.GetElement(0, 2), m.GetElement(1, 2), m.GetElement(2, 2)], dtype=float)",
    "    point = np.array([m.GetElement(0, 3), m.GetElement(1, 3), m.GetElement(2, 3)], dtype=float)",
    "",
    "    return point, nrm(x_axis), nrm(y_axis), nrm(z_axis)",
    "",
    "def copy_vtk_matrix(m):",
    "    out = vtk.vtkMatrix4x4()",
    "    out.DeepCopy(m)",
    "    return out",
    "",
    "def apply_slice_to_ras_matrix(sliceToRAS):",
    "    sliceWidget, sliceLogic, sliceNode = get_slice_node_and_widget()",
    "    sliceNode.GetSliceToRAS().DeepCopy(sliceToRAS)",
    "    sliceNode.UpdateMatrices()",
    "    sliceNode.Modified()",
    "",
    "    try:",
    "        sliceNode.SetFieldOfView(float(FIELD_OF_VIEW_MM), float(FIELD_OF_VIEW_MM), 1.0)",
    "    except Exception as e:",
    "        print(\"Could not set field of view:\", e)",
    "",
    "    try:",
    "        sliceNode.SetSliceVisible(True)",
    "        sliceNode.SetWidgetVisible(True)",
    "    except Exception:",
    "        pass",
    "",
    "    try:",
    "        sliceNode.SetSliceEdgeVisibility3D(True)",
    "    except Exception:",
    "        pass",
    "",
    "    try:",
    "        sliceWidget.sliceView().scheduleRender()",
    "    except Exception:",
    "        pass",
    "",
    "    return sliceWidget, sliceLogic, sliceNode",
    "",
    "def lock_red_slice_browsing(sliceWidget):",
    "    if not LOCK_RED_SLICE_BROWSING:",
    "        return",
    "",
    "    try:",
    "        sliceView = sliceWidget.sliceView()",
    "",
    "        observer = None",
    "        if hasattr(sliceView, \"interactorObserver\"):",
    "            try:",
    "                observer = sliceView.interactorObserver()",
    "            except Exception:",
    "                observer = None",
    "",
    "        if observer is not None:",
    "            try:",
    "                browse_slice_action = observer.BrowseSlice",
    "                observer.SetActionEnabled(browse_slice_action, False)",
    "                print(\"Disabled BrowseSlice via interactorObserver.\")",
    "                return",
    "            except Exception:",
    "                pass",
    "",
    "        # Fallback for older Slicer versions only.",
    "        # In Slicer 5.10 this method is deprecated, so it is used only if interactorObserver() fails.",
    "        if hasattr(sliceView, \"sliceViewInteractorStyle\"):",
    "            interactorStyle = sliceView.sliceViewInteractorStyle()",
    "            try:",
    "                interactorStyle.SetActionEnabled(interactorStyle.BrowseSlice, False)",
    "                print(\"Disabled BrowseSlice via sliceViewInteractorStyle fallback.\")",
    "                return",
    "            except Exception:",
    "                pass",
    "",
    "        print(\"Could not disable BrowseSlice: no compatible slice interactor API was available.\")",
    "",
    "    except Exception as e:",
    "        print(\"Could not lock Red slice browsing:\", e)",
    "",
    "def setup_slice_view(volumeNode, sliceToRAS):",
    "    sliceWidget, sliceLogic, sliceNode = get_slice_node_and_widget()",
    "    compositeNode = sliceLogic.GetSliceCompositeNode()",
    "",
    "    if compositeNode is not None:",
    "        compositeNode.SetBackgroundVolumeID(volumeNode.GetID())",
    "        compositeNode.SetForegroundOpacity(0.0)",
    "",
    "    sliceWidget, sliceLogic, sliceNode = apply_slice_to_ras_matrix(sliceToRAS)",
    "    lock_red_slice_browsing(sliceWidget)",
    "",
    "    return sliceWidget, sliceLogic, sliceNode",
    "",
    "def setup_volume_rendering(volumeNode):",
    "    try:",
    "        vrLogic = slicer.modules.volumerendering.logic()",
    "    except Exception:",
    "        print(\"Volume rendering logic not available.\")",
    "        return None",
    "",
    "    try:",
    "        displayNode = vrLogic.GetFirstVolumeRenderingDisplayNode(volumeNode)",
    "        if displayNode is None:",
    "            displayNode = vrLogic.CreateDefaultVolumeRenderingNodes(volumeNode)",
    "",
    "        preset = vrLogic.GetPresetByName(VOLUME_RENDERING_PRESET)",
    "        if preset is not None:",
    "            displayNode.GetVolumePropertyNode().Copy(preset)",
    "            print(f'Applied volume rendering preset: \"{VOLUME_RENDERING_PRESET}\"')",
    "        else:",
    "            print(f'Preset \"{VOLUME_RENDERING_PRESET}\" not found. Available presets may differ.')",
    "",
    "        displayNode.SetVisibility(True)",
    "",
    "        try:",
    "            displayNode.SetAndObserveVolumeNodeID(volumeNode.GetID())",
    "        except Exception:",
    "            pass",
    "",
    "        return displayNode",
    "",
    "    except Exception as e:",
    "        print(\"Could not enable volume rendering:\", e)",
    "        return None",
    "",
    "def setup_3d_verification_view(focal_point, section_normal, arp_normal):",
    "    lm = slicer.app.layoutManager()",
    "    threeDWidget = lm.threeDWidget(0)",
    "    if threeDWidget is None:",
    "        print(\"No 3D widget available.\")",
    "        return None",
    "",
    "    threeDView = threeDWidget.threeDView()",
    "    if threeDView is None:",
    "        print(\"No 3D view available.\")",
    "        return None",
    "",
    "    viewNode = threeDView.mrmlViewNode()",
    "    renderer = threeDView.renderWindow().GetRenderers().GetFirstRenderer()",
    "    camera = renderer.GetActiveCamera()",
    "",
    "    focal_point = np.asarray(focal_point, dtype=float)",
    "    section_normal = nrm(section_normal)",
    "    arp_normal = nrm(arp_normal)",
    "",
    "    view_dir = cross3(arp_normal, section_normal)",
    "",
    "    if np.linalg.norm(view_dir) < 1e-12:",
    "        raise ValueError(\"ARP normal and section normal are nearly parallel; cannot construct verification view.\")",
    "",
    "    view_dir = nrm(view_dir)",
    "",
    "    if THREED_VERIFICATION_VIEW_SIDE.upper() == \"MINUS\":",
    "        view_dir = -view_dir",
    "    elif THREED_VERIFICATION_VIEW_SIDE.upper() != \"PLUS\":",
    "        raise ValueError('THREED_VERIFICATION_VIEW_SIDE must be \"PLUS\" or \"MINUS\".')",
    "",
    "    view_up = arp_normal",
    "    camera_position = focal_point - CAMERA_DISTANCE_MM * view_dir",
    "",
    "    camera.SetFocalPoint(float(focal_point[0]), float(focal_point[1]), float(focal_point[2]))",
    "    camera.SetPosition(float(camera_position[0]), float(camera_position[1]), float(camera_position[2]))",
    "    camera.SetViewUp(float(view_up[0]), float(view_up[1]), float(view_up[2]))",
    "    camera.OrthogonalizeViewUp()",
    "    camera.SetParallelProjection(True)",
    "    camera.SetParallelScale(FIELD_OF_VIEW_MM / 2.0)",
    "",
    "    try:",
    "        viewNode.SetBoxVisible(False)",
    "    except Exception:",
    "        pass",
    "",
    "    try:",
    "        viewNode.SetAxisLabelsVisible(False)",
    "    except Exception:",
    "        pass",
    "",
    "    renderer.ResetCameraClippingRange()",
    "    threeDView.scheduleRender()",
    "",
    "    return threeDView",
    "",
    "def add_lm1_line_point():",
    "    if not CREATE_LM1_LINE_POINT:",
    "        return",
    "",
    "    node = slicer.mrmlScene.AddNewNodeByClass(",
    "        \"vtkMRMLMarkupsFiducialNode\",",
    "        \"OrientCSG_LM1_Line\"",
    "    )",
    "    node.CreateDefaultDisplayNodes()",
    "",
    "    p = LM1_LINE",
    "    node.AddControlPointWorld(",
    "        vtk.vtkVector3d(float(p[0]), float(p[1]), float(p[2])),",
    "        \"LM1_Line\"",
    "    )",
    "",
    "    node.SetLocked(True)",
    "",
    "    d = node.GetDisplayNode()",
    "    if d is not None:",
    "        d.SetVisibility(True)",
    "        d.SetColor(1.0, 0.0, 0.0)",
    "        d.SetSelectedColor(1.0, 0.0, 0.0)",
    "        d.SetGlyphScale(4.0)",
    "        d.SetTextScale(2.0)",
    "",
    "        try:",
    "            d.SetGlyphTypeFromString(\"Sphere3D\")",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetPointLabelsVisibility(True)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetVisibility3D(True)",
    "            d.SetVisibility2D(True)",
    "        except Exception:",
    "            pass",
    "",
    "def add_scale_bar_at_current_slice(section_label):",
    "    if not CREATE_SCALE_BAR:",
    "        return",
    "",
    "    remove_old_scale_nodes()",
    "",
    "    Psec, x_axis, y_axis, z_axis = get_current_slice_axes()",
    "",
    "    x_offset = -(FIELD_OF_VIEW_MM / 2.0 - SCALE_BAR_MARGIN_MM - SCALE_BAR_LENGTH_MM / 2.0)",
    "    y_offset = -(FIELD_OF_VIEW_MM / 2.0 - SCALE_BAR_MARGIN_MM)",
    "",
    "    center = Psec + x_offset * x_axis + y_offset * y_axis",
    "",
    "    p1 = center - 0.5 * SCALE_BAR_LENGTH_MM * x_axis",
    "    p2 = center + 0.5 * SCALE_BAR_LENGTH_MM * x_axis",
    "",
    "    line = slicer.mrmlScene.AddNewNodeByClass(",
    "        \"vtkMRMLMarkupsLineNode\",",
    "        f\"OrientCSG_scale_{section_label}_10mm\"",
    "    )",
    "    line.CreateDefaultDisplayNodes()",
    "    line.AddControlPointWorld(",
    "        vtk.vtkVector3d(float(p1[0]), float(p1[1]), float(p1[2])),",
    "        \"\"",
    "    )",
    "    line.AddControlPointWorld(",
    "        vtk.vtkVector3d(float(p2[0]), float(p2[1]), float(p2[2])),",
    "        \"\"",
    "    )",
    "    line.SetLocked(True)",
    "",
    "    d = line.GetDisplayNode()",
    "    if d is not None:",
    "        d.SetVisibility(True)",
    "        d.SetColor(1.0, 1.0, 1.0)",
    "        d.SetSelectedColor(1.0, 1.0, 1.0)",
    "        d.SetLineThickness(0.75)",
    "        d.SetGlyphScale(0.35)",
    "        d.SetTextScale(1.0)",
    "",
    "        try:",
    "            d.SetPointLabelsVisibility(False)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetPropertiesLabelVisibility(False)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetVisibility3D(False)",
    "            d.SetVisibility2D(True)",
    "        except Exception:",
    "            pass",
    "",
    "    label_point = center + 1.35 * y_axis",
    "",
    "    label = slicer.mrmlScene.AddNewNodeByClass(",
    "        \"vtkMRMLMarkupsFiducialNode\",",
    "        f\"OrientCSG_scale_{section_label}_label\"",
    "    )",
    "    label.CreateDefaultDisplayNodes()",
    "    label.AddControlPointWorld(",
    "        vtk.vtkVector3d(float(label_point[0]), float(label_point[1]), float(label_point[2])),",
    "        \"10 mm\"",
    "    )",
    "    label.SetLocked(True)",
    "",
    "    ld = label.GetDisplayNode()",
    "    if ld is not None:",
    "        ld.SetVisibility(True)",
    "        ld.SetColor(1.0, 1.0, 1.0)",
    "        ld.SetSelectedColor(1.0, 1.0, 1.0)",
    "        ld.SetGlyphScale(0.001)",
    "        ld.SetTextScale(1.6)",
    "",
    "        try:",
    "            ld.SetGlyphTypeFromString(\"None\")",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            ld.SetPointLabelsVisibility(True)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            ld.SetVisibility3D(False)",
    "            ld.SetVisibility2D(True)",
    "        except Exception:",
    "            pass",
    "",
    "    print(f\"Created {SCALE_BAR_LENGTH_MM:g} mm scale bar at current slice position.\")",
    "",
    "def add_arp_plane():",
    "    if not CREATE_ARP_PLANE:",
    "        return",
    "",
    "    node = slicer.mrmlScene.AddNewNodeByClass(\"vtkMRMLMarkupsPlaneNode\", \"OrientCSG_ARP\")",
    "",
    "    try:",
    "        node.SetOriginWorld(",
    "            float(ARP_ORIGIN[0]),",
    "            float(ARP_ORIGIN[1]),",
    "            float(ARP_ORIGIN[2])",
    "        )",
    "    except Exception:",
    "        node.SetOriginWorld(ARP_ORIGIN)",
    "",
    "    try:",
    "        node.SetNormalWorld(",
    "            float(ARP_NORMAL[0]),",
    "            float(ARP_NORMAL[1]),",
    "            float(ARP_NORMAL[2])",
    "        )",
    "    except Exception:",
    "        node.SetNormalWorld(ARP_NORMAL)",
    "",
    "    try:",
    "        node.SetSizeWorld([90.0, 90.0])",
    "    except Exception:",
    "        pass",
    "",
    "    node.SetLocked(True)",
    "    node.CreateDefaultDisplayNodes()",
    "",
    "    d = node.GetDisplayNode()",
    "    if d is not None:",
    "        d.SetVisibility(True)",
    "        d.SetColor(0.0, 1.0, 0.0)",
    "        d.SetSelectedColor(0.0, 1.0, 0.0)",
    "        d.SetOpacity(0.45)",
    "",
    "        try:",
    "            d.SetFillVisibility(True)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetOutlineVisibility(True)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetLineThickness(0.8)",
    "        except Exception:",
    "            pass",
    "",
    "        try:",
    "            d.SetVisibility3D(True)",
    "            d.SetVisibility2D(False)",
    "        except Exception:",
    "            pass",
    "",
    "def refresh_orientcsg_scale():",
    "    add_scale_bar_at_current_slice(SECTION_LABEL.upper())",
    "",
    "def restore_view():",
    "    global ORIENTCSG_INITIAL_SLICE_TO_RAS",
    "    global ORIENTCSG_INITIAL_PSEC",
    "    global ORIENTCSG_INITIAL_Z_AXIS",
    "",
    "    if ORIENTCSG_INITIAL_SLICE_TO_RAS is None:",
    "        raise ValueError(\"No stored OrientCSG orientation found. Run the full block once first.\")",
    "",
    "    apply_slice_to_ras_matrix(ORIENTCSG_INITIAL_SLICE_TO_RAS)",
    "    refresh_orientcsg_scale()",
    "    setup_3d_verification_view(",
    "        ORIENTCSG_INITIAL_PSEC,",
    "        ORIENTCSG_INITIAL_Z_AXIS,",
    "        ARP_NORMAL",
    "    )",
    "",
    "    print(\"Restored OrientCSG mandibular slice orientation, 3D verification view, and scale.\")",
    "",
    "# ============================================================",
    "# Run",
    "# ============================================================",
    "",
    "remove_old_orientcsg_nodes()",
    "",
    "sliceToRAS, X_AXIS, Y_AXIS, Z_AXIS = make_slice_to_ras(PSEC, NORMAL, X_SCREEN_REFERENCE, Y_PREFERRED)",
    "",
    "volumeNode = find_volume_node(VOLUME_NAME)",
    "",
    "ORIENTCSG_INITIAL_SLICE_TO_RAS = copy_vtk_matrix(sliceToRAS)",
    "ORIENTCSG_INITIAL_PSEC = np.asarray(PSEC, dtype=float)",
    "ORIENTCSG_INITIAL_Z_AXIS = np.asarray(Z_AXIS, dtype=float)",
    "",
    "sliceWidget, sliceLogic, sliceNode = setup_slice_view(volumeNode, sliceToRAS)",
    "",
    "add_arp_plane()",
    "add_lm1_line_point()",
    "add_scale_bar_at_current_slice(SECTION_LABEL.upper())",
    "",
    "vrDisplayNode = setup_volume_rendering(volumeNode)",
    "threeDView = setup_3d_verification_view(PSEC, Z_AXIS, ARP_NORMAL)",
    "",
    "print(\"\\n================ ORIENTCSG / SLICER MANDIBLE TEST ================\")",
    "print(\"Volume:\", volumeNode.GetName())",
    "print(\"Section:\", SECTION_LABEL.upper())",
    "print(\"Slice view:\", SLICE_VIEW_NAME)",
    "print(\"Field of view, mm:\", FIELD_OF_VIEW_MM)",
    "print(\"Camera distance, mm:\", CAMERA_DISTANCE_MM)",
    "print(\"Volume rendering preset:\", VOLUME_RENDERING_PRESET)",
    "print(\"3D verification view side:\", THREED_VERIFICATION_VIEW_SIDE)",
    "print(\"Red slice browsing locked:\", LOCK_RED_SLICE_BROWSING)",
    "",
    "print(\"\\nPSEC, Slicer RAS:\")",
    "print(PSEC)",
    "",
    "print(\"\\nSliceToRAS axes, Slicer RAS:\")",
    "print(\"X screen:\", X_AXIS)",
    "print(\"Y screen:\", Y_AXIS)",
    "print(\"Z normal/view:\", Z_AXIS)",
    "",
    "print(\"\\n3D verification view logic:\")",
    "print(\"View direction = cross(ARP normal, section normal)\")",
    "print(\"View up = ARP normal\")",
    "print(\"Therefore ARP should appear horizontal and section plane vertical.\")",
    "",
    "print(\"\\nKey computed geometry, Slicer RAS:\")",
    "print(\"LM1_Line:\", LM1_LINE)",
    "print(\"ARP_Origin:\", ARP_ORIGIN)",
    "print(\"ARP_Normal/Vec_Penp:\", ARP_NORMAL)",
    "",
    "print(\"\\nChecks:\")",
    "print(\"dot(X,Y) =\", dot3(X_AXIS, Y_AXIS))",
    "print(\"dot(X,Z) =\", dot3(X_AXIS, Z_AXIS))",
    "print(\"dot(Y,Z) =\", dot3(Y_AXIS, Z_AXIS))",
    "print(\"det approx =\", dot3(cross3(X_AXIS, Y_AXIS), Z_AXIS))",
    "",
    "print(\"\\nAvailable helper commands:\")",
    "print('Run restore_view() to restore the original slice orientation, 3D verification view, and scale.')",
    "print('Run refresh_orientcsg_scale() to recreate the 10 mm scale bar at the current slice position.')"
  )

  paste(code, collapse = "\n")
}
